# Generated by Django 3.0.8 on 2020-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_author', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
