# Generated by Django 3.0.8 on 2020-07-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20200725_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(default='default_post.jpg', upload_to='post_images'),
        ),
    ]
