# Generated by Django 3.0.8 on 2020-07-27 13:37

import blogapp.models
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20200726_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='yeet', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=blogapp.models.Category.get_default_pk, on_delete=django.db.models.deletion.DO_NOTHING, to='blogapp.Category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
