# Generated by Django 3.0.8 on 2020-08-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20200727_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='blog_posts',
            new_name='post',
        ),
    ]
