# Generated by Django 3.0.8 on 2020-08-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20200802_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='post',
            new_name='posts',
        ),
    ]
